# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\"w\n\rImageResponse\x12\x33\n\x0bresult_dict\x18\x01 \x03(\x0b\x32\x1e.ImageResponse.ResultDictEntry\x1a\x31\n\x0fResultDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32?\n\x0cImageService\x12/\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGERESPONSE_RESULTDICTENTRY._options = None
  _IMAGERESPONSE_RESULTDICTENTRY._serialized_options = b'8\001'
  _IMAGEREQUEST._serialized_start=23
  _IMAGEREQUEST._serialized_end=57
  _IMAGERESPONSE._serialized_start=59
  _IMAGERESPONSE._serialized_end=178
  _IMAGERESPONSE_RESULTDICTENTRY._serialized_start=129
  _IMAGERESPONSE_RESULTDICTENTRY._serialized_end=178
  _IMAGESERVICE._serialized_start=180
  _IMAGESERVICE._serialized_end=243
# @@protoc_insertion_point(module_scope)
